package com.mesabrook.ib.init;

import com.mesabrook.ib.Main;
import com.mesabrook.ib.util.Reference;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;

public class ModSounds
{
	public static final SoundEvent ATM_BEEP;
	public static final SoundEvent ZAP;
	public static final SoundEvent BOLLARD;
	public static final SoundEvent OWO_SFX;
	public static final SoundEvent RZ_TROPHY;
	public static final SoundEvent CSX_TROPHY;
	public static final SoundEvent TLZ_TROPHY;
	public static final SoundEvent LW_TROPHY;
	public static final SoundEvent MD_TROPHY;
	public static final SoundEvent SVV_TROPHY;
	public static final SoundEvent KT_TROPHY;
	public static final SoundEvent TROPHY_BREAK;
	public static final SoundEvent OOF;
	public static final SoundEvent CAN_OPEN;
	public static final SoundEvent CAN_CLOSE;
	public static final SoundEvent CHEESE_PLACE;
	public static final SoundEvent CHEESE_CLICK;
	public static final SoundEvent PIE;
	public static final SoundEvent FISH;
	public static final SoundEvent FISH_FULL;
	public static final SoundEvent NO;
	public static final SoundEvent NV;
	public static final SoundEvent VEST;
	public static final SoundEvent SAFETY;
	public static final SoundEvent YOINK;
	public static final SoundEvent BEANED;
	public static final SoundEvent BONG;
	public static final SoundEvent BONK;
	public static final SoundEvent POP;
	public static final SoundEvent POP_SINGLE;
	public static final SoundEvent SPREE;
	public static final SoundEvent OWIE;
	public static final SoundEvent DOVE;
	public static final SoundEvent CPW;
	public static final SoundEvent SPLOOT;
	public static final SoundEvent OWO2;
	public static final SoundEvent OWO3;
	public static final SoundEvent PUFF;
	public static final SoundEvent WOOSH;
	public static final SoundEvent DOOT;
	public static final SoundEvent SHEP;
	public static final SoundEvent TRUMPET;
	public static final SoundEvent HEARTBEAT;
	public static final SoundEvent SQUID;
	public static final SoundEvent REVERB;
	public static final SoundEvent BURP;
	public static final SoundEvent QUACK;
	public static final SoundEvent QUACKBOOM;
	public static final SoundEvent BAKA;
	public static final SoundEvent MALLET;
	public static final SoundEvent POLICE_HELMET;
	public static final SoundEvent KEKW;
	public static final SoundEvent TWO_YEARS;
	public static final SoundEvent LEOTEU_ON;
	public static final SoundEvent LEOTEU_OFF;
	public static final SoundEvent EXP;
	public static final SoundEvent LOUDBONG;
	public static final SoundEvent BOOK_OPEN;
	public static final SoundEvent BOOK_CLOSE;
	public static final SoundEvent MH_OPEN;
	public static final SoundEvent MH_CLOSE;
	public static final SoundEvent JINGLES;
	public static final SoundEvent RIP;
	public static final SoundEvent SUS1;
	public static final SoundEvent SUS2;
	public static final SoundEvent SPICY;
	public static final SoundEvent OK1;
	public static final SoundEvent OK2;
	public static final SoundEvent DEATH;
	public static final SoundEvent WATERPHONE;
	public static final SoundEvent HEAL;
	public static final SoundEvent GAVEL;
	public static final SoundEvent SPONGE_EQUIP;
	public static final SoundEvent SPONGE_USE;
	public static final SoundEvent FART_1;
	public static final SoundEvent FART_2;
	public static final SoundEvent FART_3;
	public static final SoundEvent FART_4;
	public static final SoundEvent FART_5;
	public static final SoundEvent COUGH_M;
	public static final SoundEvent COUGH_F;
	public static final SoundEvent CHISEL;
	public static final SoundEvent RATION_OPEN;
	public static final SoundEvent TAPE_MEASURE_OPEN;
	public static final SoundEvent TAPE_MEASURE_CLOSE;
	public static final SoundEvent TOILET_1;
	public static final SoundEvent TOILET_2;
	public static final SoundEvent TOILET_3;
	public static final SoundEvent URINAL;
	public static final SoundEvent WC_ON;
	public static final SoundEvent WC_OFF;
	public static final SoundEvent FRIDGE_OPEN;
	public static final SoundEvent FRIDGE_CLOSE;
	public static final SoundEvent COMING_OUT;
	public static final SoundEvent DESK_BELL;
	public static final SoundEvent DESK_BELL_AF;
	public static final SoundEvent CASH_OUT;
	public static final SoundEvent CARD_OUT;

	// Meme Records integration
	public static final SoundEvent AMALTHEA;
	public static final SoundEvent NYAN;
	public static final SoundEvent USSR1;
	public static final SoundEvent USSR2;
	public static final SoundEvent BOOEY;
	public static final SoundEvent DOLAN;
	public static final SoundEvent MURICA;
	public static final SoundEvent PIGSTEP;
	public static final SoundEvent KRAB_BORG;
	public static final SoundEvent KRAB_BORG_FULL;
	public static final SoundEvent MS_XP;
	public static final SoundEvent COOKING;
	public static final SoundEvent MEMORY;
	public static final SoundEvent WIDE;
	public static final SoundEvent PIANO;

	// Holiday Records
	public static final SoundEvent SPOOKY;
	public static final SoundEvent RITZ;
	public static final SoundEvent HL3;
	public static final SoundEvent HALLOW;
	public static final SoundEvent CAKE;

	// Plastic SoundType
	public static final SoundEvent PLASTIC_PLACE;
	public static final SoundEvent PLASTIC_BREAK;
	public static final SoundEvent PLASTIC_HIT;
	public static final SoundEvent PLASTIC_STEP;
	public static final SoundEvent PLASTIC_LAND;

	// Manhole SoundType
	public static final SoundEvent MANHOLE_OPEN;
	public static final SoundEvent MANHOLE_CLOSE;
	public static final SoundEvent MANHOLE_PLACE;
	public static final SoundEvent MANHOLE_BREAK;
	public static final SoundEvent MANHOLE_STEP;

	// Warp Metro
	public static final SoundEvent TM_BEEP;

	// Comms
	public static final SoundEvent RADIO_CLOSE;
	public static final SoundEvent PHONE_ACTIVATE;
	public static final SoundEvent DING_1;
	public static final SoundEvent DING_2;
	public static final SoundEvent DING_3;
	public static final SoundEvent DING_4;
	public static final SoundEvent DING_5;
	public static final SoundEvent DING_6;
	public static final SoundEvent DING_7;
	public static final SoundEvent DING_8;
	public static final SoundEvent DING_9;
	public static final SoundEvent DING_10;
	public static final SoundEvent OUTGOING_CALL;
	public static final SoundEvent SIT;
	public static final SoundEvent SIT_1;
	public static final SoundEvent SIT_2;
	public static final SoundEvent SIT_3;
	public static final SoundEvent SIT_4;
	public static final SoundEvent SIT_5;
	public static final SoundEvent STARTCALL;
	public static final SoundEvent ENDCALL;
	public static final SoundEvent PHONE_UNLOCK;
	public static final SoundEvent BUSY;
	public static final SoundEvent ALERT_TONE;
	public static final SoundEvent PHONE_OFF;
	public static final SoundEvent MINEDROID_STARTUP;
	public static final SoundEvent PHONE_BATTERY_LOW;
	public static final SoundEvent PHONE_UNBOX;
	public static final SoundEvent ALERT;
	public static final SoundEvent NORMAL_BOOT;
	public static final SoundEvent OOBE_BOOT;
	public static final SoundEvent XP_STARTUP;
	public static final SoundEvent AERO_STARTUP;

	// Ringtones
	public static final SoundEvent RING_1;
	public static final SoundEvent RING_2;
	public static final SoundEvent RING_3;
	public static final SoundEvent RING_4;
	public static final SoundEvent RING_5;
	public static final SoundEvent RING_6;
	public static final SoundEvent RING_7;
	public static final SoundEvent RING_8;
	public static final SoundEvent RING_9;
	public static final SoundEvent RING_10;
	public static final SoundEvent RING_11;
	public static final SoundEvent RING_12;
	public static final SoundEvent RING_13;
	public static final SoundEvent RING_14;
	public static final SoundEvent RING_15;
	public static final SoundEvent RING_16;
	public static final SoundEvent RING_17;
	public static final SoundEvent RING_18;
	public static final SoundEvent RING_19;
	public static final SoundEvent RING_20;
	public static final SoundEvent RING_21;
	public static final SoundEvent RING_22;
	public static final SoundEvent RING_23;
	public static final SoundEvent RING_24;
	public static final SoundEvent RING_25;

	// DTMF Phone Tones
	public static final SoundEvent DTMF_0;
	public static final SoundEvent DTMF_1;
	public static final SoundEvent DTMF_2;
	public static final SoundEvent DTMF_3;
	public static final SoundEvent DTMF_4;
	public static final SoundEvent DTMF_5;
	public static final SoundEvent DTMF_6;
	public static final SoundEvent DTMF_7;
	public static final SoundEvent DTMF_8;
	public static final SoundEvent DTMF_9;
	public static final SoundEvent PHONE_CRASH;
	public static final SoundEvent PHONE_BOOTUP;
	public static final SoundEvent BATTERY_LOW;
	
	// Self-Checkout
	public static final SoundEvent BILL_ACCEPTOR;
	public static final SoundEvent COIN_SLOT;
	public static final SoundEvent POS_CASHBACK;
	public static final SoundEvent POS_PAYMENT_TYPE;
	public static final SoundEvent POS_SCAN;
	public static final SoundEvent POS_SCANNER_BEEP;
	public static final SoundEvent POS_SCANNER_MULTIBEEP;
	public static final SoundEvent POS_TAKE_CARD;
	public static final SoundEvent POS_USE_PINPAD;
	public static final SoundEvent POS_WELCOME;

	static
	{
		KT_TROPHY = addSoundsToRegistry("kreative");
		ATM_BEEP = addSoundsToRegistry("atm_button_beep");
		ZAP = addSoundsToRegistry("zap");
		BOLLARD = addSoundsToRegistry("bollard_sound");
		OWO_SFX = addSoundsToRegistry("owo");
		RZ_TROPHY = addSoundsToRegistry("rz_trophy");
		CSX_TROPHY = addSoundsToRegistry("csx_trophy");
		TLZ_TROPHY = addSoundsToRegistry("tlz_trophy");
		LW_TROPHY = addSoundsToRegistry("lw_trophy");
		MD_TROPHY = addSoundsToRegistry("md_trophy");
		SVV_TROPHY = addSoundsToRegistry("svv_trophy");
		TROPHY_BREAK = addSoundsToRegistry("trophy_break");
		OOF = addSoundsToRegistry("oof");
		CAN_OPEN = addSoundsToRegistry("can_open");
		CAN_CLOSE = addSoundsToRegistry("can_close");
		CHEESE_PLACE = addSoundsToRegistry("cheese_place");
		CHEESE_CLICK = addSoundsToRegistry("cheese_click");
		PIE = addSoundsToRegistry("pie");
		FISH = addSoundsToRegistry("fish");
		FISH_FULL = addSoundsToRegistry("fish_full");
		NO = addSoundsToRegistry("no");
		NV = addSoundsToRegistry("nv");
		VEST = addSoundsToRegistry("vest");
		SAFETY = addSoundsToRegistry("safety");
		YOINK = addSoundsToRegistry("yoink");
		BEANED = addSoundsToRegistry("beaned");
		BONG = addSoundsToRegistry("bong");
		BONK = addSoundsToRegistry("bonk");
		POP = addSoundsToRegistry("pop");
		POP_SINGLE = addSoundsToRegistry("pop_single");
		SPREE = addSoundsToRegistry("spree");
		OWIE = addSoundsToRegistry("owie");
		DOVE = addSoundsToRegistry("dove");
		CPW = addSoundsToRegistry("cpw");
		SPLOOT = addSoundsToRegistry("sploot");
		OWO2 = addSoundsToRegistry("new_owo");
		OWO3 = addSoundsToRegistry("new_owo_short");
		PUFF = addSoundsToRegistry("puff");
		WOOSH = addSoundsToRegistry("woosh");
		DOOT = addSoundsToRegistry("doot");
		SHEP = addSoundsToRegistry("shep");
		TRUMPET = addSoundsToRegistry("trumpet");
		HEARTBEAT = addSoundsToRegistry("hb");
		SQUID = addSoundsToRegistry("squidward");
		REVERB = addSoundsToRegistry("reverb");
		BURP = addSoundsToRegistry("burp");
		QUACK = addSoundsToRegistry("duck");
		QUACKBOOM = addSoundsToRegistry("duckboom");
		BAKA = addSoundsToRegistry("baka");
		MALLET = addSoundsToRegistry("mallet");
		POLICE_HELMET = addSoundsToRegistry("police_helmet");
		KEKW = addSoundsToRegistry("kekw");
		TWO_YEARS = addSoundsToRegistry("two_years");
		LEOTEU_ON = addSoundsToRegistry("leoteu_on");
		LEOTEU_OFF = addSoundsToRegistry("leoteu_off");
		EXP = addSoundsToRegistry("exp");
		LOUDBONG = addSoundsToRegistry("loudbong");
		BOOK_OPEN = addSoundsToRegistry("book_open");
		BOOK_CLOSE = addSoundsToRegistry("book_close");
		MH_OPEN = addSoundsToRegistry("mh_open");
		MH_CLOSE = addSoundsToRegistry("mh_close");
		JINGLES = addSoundsToRegistry("jingles");
		RIP = addSoundsToRegistry("rip");
		SUS1 = addSoundsToRegistry("sus1");
		SUS2 = addSoundsToRegistry("sus2");
		SPICY = addSoundsToRegistry("spicy");
		OK1 = addSoundsToRegistry("ok1");
		OK2 = addSoundsToRegistry("ok2");
		DEATH = addSoundsToRegistry("death");
		WATERPHONE = addSoundsToRegistry("waterphone");
		HEAL = addSoundsToRegistry("heal");
		GAVEL = addSoundsToRegistry("gavel");
		SPONGE_EQUIP = addSoundsToRegistry("sponge_equip");
		SPONGE_USE = addSoundsToRegistry("sponge_use");
		FART_1 = addSoundsToRegistry("fart_1");
		FART_2 = addSoundsToRegistry("fart_2");
		FART_3 = addSoundsToRegistry("fart_3");
		FART_4 = addSoundsToRegistry("fart_4");
		FART_5 = addSoundsToRegistry("fart_5");
		COUGH_M = addSoundsToRegistry("cough_m");
		COUGH_F = addSoundsToRegistry("cough_f");
		CHISEL = addSoundsToRegistry("chisel");
		RATION_OPEN = addSoundsToRegistry("ration_open");
		TAPE_MEASURE_OPEN = addSoundsToRegistry("tape_measure_open");
		TAPE_MEASURE_CLOSE = addSoundsToRegistry("tape_measure_close");
		TOILET_1 = addSoundsToRegistry("toilet_1");
		TOILET_2 = addSoundsToRegistry("toilet_2");
		TOILET_3 = addSoundsToRegistry("toilet_3");
		URINAL = addSoundsToRegistry("urinal");
		WC_OFF = addSoundsToRegistry("wireless_charge_off");
		WC_ON = addSoundsToRegistry("wireless_charge_on");
		PIANO = addSoundsToRegistry("piano");
		COMING_OUT = addSoundsToRegistry("coming_out");
		DESK_BELL = addSoundsToRegistry("desk_bell");
		DESK_BELL_AF = addSoundsToRegistry("desk_bell_af");
		CASH_OUT = addSoundsToRegistry("cash_out");
		CARD_OUT = addSoundsToRegistry("card_out");

		// Begin Records
		AMALTHEA = addSoundsToRegistry("amalthea");
		NYAN = addSoundsToRegistry("nyan");
		USSR1 = addSoundsToRegistry("ussr1");
		USSR2 = addSoundsToRegistry("ussr2");
		BOOEY = addSoundsToRegistry("baba_booey");
		DOLAN = addSoundsToRegistry("dolan");
		MURICA = addSoundsToRegistry("murica");
		PIGSTEP = addSoundsToRegistry("pigstep");
		KRAB_BORG = addSoundsToRegistry("krab_borg");
		KRAB_BORG_FULL = addSoundsToRegistry("krab_borg_full");
		MS_XP = addSoundsToRegistry("ms_xp");
		SPOOKY = addSoundsToRegistry("spooky");
		RITZ = addSoundsToRegistry("ritz");
		HL3 = addSoundsToRegistry("hl3");
		COOKING = addSoundsToRegistry("cooking");
		MEMORY = addSoundsToRegistry("memory");
		WIDE = addSoundsToRegistry("wide");
		HALLOW = addSoundsToRegistry("hallow");
		CAKE = addSoundsToRegistry("cake");
		FRIDGE_OPEN = addSoundsToRegistry("fridge_open");
		FRIDGE_CLOSE = addSoundsToRegistry("fridge_close");

		// Plastic SoundType
		PLASTIC_BREAK = addSoundsToRegistry("plastic_break");
		PLASTIC_HIT = addSoundsToRegistry("plastic_hit");
		PLASTIC_LAND = addSoundsToRegistry("plastic_land");
		PLASTIC_PLACE = addSoundsToRegistry("plastic_place");
		PLASTIC_STEP = addSoundsToRegistry("plastic_step");

		// Manhole SoundType
		MANHOLE_OPEN = addSoundsToRegistry("manhole_open");
		MANHOLE_CLOSE = addSoundsToRegistry("manhole_close");
		MANHOLE_PLACE = addSoundsToRegistry("manhole_place");
		MANHOLE_BREAK = addSoundsToRegistry("manhole_break");
		MANHOLE_STEP = addSoundsToRegistry("manhole_step");

		// Warp Metro
		TM_BEEP = addSoundsToRegistry("tm_beep");

		// Comms
		RADIO_CLOSE = addSoundsToRegistry("radio_close");
		DING_1 = addSoundsToRegistry("ding_1");
		DING_2 = addSoundsToRegistry("ding_2");
		DING_3 = addSoundsToRegistry("ding_3");
		DING_4 = addSoundsToRegistry("ding_4");
		DING_5 = addSoundsToRegistry("ding_5");
		DING_6 = addSoundsToRegistry("ding_6");
		DING_7 = addSoundsToRegistry("ding_7");
		DING_8 = addSoundsToRegistry("ding_8");
		DING_9 = addSoundsToRegistry("ding_9");
		DING_10 = addSoundsToRegistry("ding_10");
		OUTGOING_CALL = addSoundsToRegistry("outgoingcall");
		SIT = addSoundsToRegistry("sit");
		SIT_1 = addSoundsToRegistry("sit_1");
		SIT_2 = addSoundsToRegistry("sit_2");
		SIT_3 = addSoundsToRegistry("sit_3");
		SIT_4 = addSoundsToRegistry("sit_4");
		SIT_5 = addSoundsToRegistry("sit_5");
		STARTCALL = addSoundsToRegistry("startcall");
		ENDCALL = addSoundsToRegistry("endcall");
		PHONE_ACTIVATE = addSoundsToRegistry("welcome");
		PHONE_UNLOCK = addSoundsToRegistry("phone_unlock");
		BUSY = addSoundsToRegistry("busy");
		ALERT_TONE = addSoundsToRegistry("alert_tone");
		PHONE_OFF = addSoundsToRegistry("phone_off");
		MINEDROID_STARTUP = addSoundsToRegistry("minedroid_startup");
		PHONE_CRASH = addSoundsToRegistry("phone_crash");
		PHONE_BATTERY_LOW = addSoundsToRegistry("phone_battery_low");
		PHONE_BOOTUP = addSoundsToRegistry("minedroid_firstboot");
		BATTERY_LOW = addSoundsToRegistry("battery_low");
		PHONE_UNBOX = addSoundsToRegistry("phone_unbox");
		ALERT = addSoundsToRegistry("alert");
		NORMAL_BOOT = addSoundsToRegistry("normal_boot");
		OOBE_BOOT = addSoundsToRegistry("oobe_startup");
		XP_STARTUP = addSoundsToRegistry("xp_startup");
		AERO_STARTUP = addSoundsToRegistry("aero_startup");

		// Ringtones
		RING_1 = addSoundsToRegistry("ring_1");
		RING_2 = addSoundsToRegistry("ring_2");
		RING_3 = addSoundsToRegistry("ring_3");
		RING_4 = addSoundsToRegistry("ring_4");
		RING_5 = addSoundsToRegistry("ring_5");
		RING_6 = addSoundsToRegistry("ring_6");
		RING_7 = addSoundsToRegistry("ring_7");
		RING_8 = addSoundsToRegistry("ring_8");
		RING_9 = addSoundsToRegistry("ring_9");
		RING_10 = addSoundsToRegistry("ring_10");
		RING_11 = addSoundsToRegistry("ring_11");
		RING_12 = addSoundsToRegistry("ring_12");
		RING_13 = addSoundsToRegistry("ring_13");
		RING_14 = addSoundsToRegistry("ring_14");
		RING_15 = addSoundsToRegistry("ring_15");
		RING_16 = addSoundsToRegistry("ring_16");
		RING_17 = addSoundsToRegistry("ring_17");
		RING_18 = addSoundsToRegistry("ring_18");
		RING_19 = addSoundsToRegistry("ring_19");
		RING_20 = addSoundsToRegistry("ring_20");
		RING_21 = addSoundsToRegistry("ring_21");
		RING_22 = addSoundsToRegistry("ring_22");
		RING_23 = addSoundsToRegistry("ring_23");
		RING_24 = addSoundsToRegistry("ring_24");
		RING_25 = addSoundsToRegistry("ring_25");

		// DTMF Phone Tones
		DTMF_0 = addSoundsToRegistry("dtmf_0");
		DTMF_1 = addSoundsToRegistry("dtmf_1");
		DTMF_2 = addSoundsToRegistry("dtmf_2");
		DTMF_3 = addSoundsToRegistry("dtmf_3");
		DTMF_4 = addSoundsToRegistry("dtmf_4");
		DTMF_5 = addSoundsToRegistry("dtmf_5");
		DTMF_6 = addSoundsToRegistry("dtmf_6");
		DTMF_7 = addSoundsToRegistry("dtmf_7");
		DTMF_8 = addSoundsToRegistry("dtmf_8");
		DTMF_9 = addSoundsToRegistry("dtmf_9");
		
		// Self-checkout
		BILL_ACCEPTOR = addSoundsToRegistry("bill_acceptor");
		COIN_SLOT = addSoundsToRegistry("coin_slot");
		POS_CASHBACK = addSoundsToRegistry("pos_cashback");
		POS_PAYMENT_TYPE = addSoundsToRegistry("pos_payment_type");
		POS_SCAN = addSoundsToRegistry("pos_scan");
		POS_SCANNER_BEEP = addSoundsToRegistry("pos_scanner_beep");
		POS_SCANNER_MULTIBEEP = addSoundsToRegistry("pos_scanner_multibeep");
		POS_TAKE_CARD = addSoundsToRegistry("pos_take_card");
		POS_USE_PINPAD = addSoundsToRegistry("pos_use_pinpad");
		POS_WELCOME = addSoundsToRegistry("pos_welcome");
	}

	private static SoundEvent addSoundsToRegistry(String soundId)
	{
		ResourceLocation shotSoundLocation = new ResourceLocation(Reference.MODID, soundId);
		SoundEvent soundEvent = new SoundEvent(shotSoundLocation);
		soundEvent.setRegistryName(shotSoundLocation);
		return soundEvent;
	}

	@EventBusSubscriber
	public static class SoundRegisterListener
	{
		@SubscribeEvent
		public static void registerSoundEvents(RegistryEvent.Register<SoundEvent> event)
		{
			try
			{
				event.getRegistry().registerAll(ModSounds.KT_TROPHY);			
				event.getRegistry().registerAll(ModSounds.ATM_BEEP);
				event.getRegistry().registerAll(ModSounds.BOLLARD);
				event.getRegistry().registerAll(ModSounds.CASH_OUT);
				event.getRegistry().registerAll(ModSounds.OWO_SFX);
				event.getRegistry().registerAll(ModSounds.WIDE);
				event.getRegistry().registerAll(ModSounds.RZ_TROPHY);
				event.getRegistry().registerAll(ModSounds.CSX_TROPHY);
				event.getRegistry().registerAll(ModSounds.TLZ_TROPHY);
				event.getRegistry().registerAll(ModSounds.LW_TROPHY);
				event.getRegistry().registerAll(ModSounds.MD_TROPHY);
				event.getRegistry().registerAll(ModSounds.SVV_TROPHY);
				event.getRegistry().registerAll(ModSounds.TROPHY_BREAK);
				event.getRegistry().registerAll(ModSounds.OOF);
				event.getRegistry().registerAll(ModSounds.CAN_OPEN);
				event.getRegistry().registerAll(ModSounds.CAN_CLOSE);
				event.getRegistry().registerAll(ModSounds.CHEESE_CLICK);
				event.getRegistry().registerAll(ModSounds.CHEESE_PLACE);
				event.getRegistry().registerAll(ModSounds.PIE);
				event.getRegistry().registerAll(ModSounds.AMALTHEA);
				event.getRegistry().registerAll(ModSounds.NYAN);
				event.getRegistry().registerAll(ModSounds.USSR1);
				event.getRegistry().registerAll(ModSounds.USSR2);
				event.getRegistry().registerAll(ModSounds.BOOEY);
				event.getRegistry().registerAll(ModSounds.DOLAN);
				event.getRegistry().registerAll(ModSounds.MURICA);
				event.getRegistry().registerAll(ModSounds.PIGSTEP);
				event.getRegistry().registerAll(ModSounds.KRAB_BORG);
				event.getRegistry().registerAll(ModSounds.KRAB_BORG_FULL);
				event.getRegistry().registerAll(ModSounds.FISH);
				event.getRegistry().registerAll(ModSounds.FISH_FULL);
				event.getRegistry().registerAll(ModSounds.NO);
				event.getRegistry().registerAll(ModSounds.NV);
				event.getRegistry().registerAll(ModSounds.VEST);
				event.getRegistry().registerAll(ModSounds.SAFETY);
				event.getRegistry().registerAll(ModSounds.YOINK);
				event.getRegistry().registerAll(ModSounds.BEANED);
				event.getRegistry().registerAll(ModSounds.BONG);
				event.getRegistry().registerAll(ModSounds.BONK);
				event.getRegistry().registerAll(ModSounds.POP);
				event.getRegistry().registerAll(ModSounds.POP_SINGLE);
				event.getRegistry().registerAll(ModSounds.SPREE);
				event.getRegistry().registerAll(ModSounds.OWIE);
				event.getRegistry().registerAll(ModSounds.DOVE);
				event.getRegistry().registerAll(ModSounds.MS_XP);
				event.getRegistry().registerAll(ModSounds.PLASTIC_PLACE);
				event.getRegistry().registerAll(ModSounds.PLASTIC_BREAK);
				event.getRegistry().registerAll(ModSounds.PLASTIC_HIT);
				event.getRegistry().registerAll(ModSounds.PLASTIC_LAND);
				event.getRegistry().registerAll(ModSounds.PLASTIC_STEP);
				event.getRegistry().registerAll(ModSounds.CPW);
				event.getRegistry().registerAll(ModSounds.SPLOOT);
				event.getRegistry().registerAll(ModSounds.OWO2);
				event.getRegistry().registerAll(ModSounds.OWO3);
				event.getRegistry().registerAll(ModSounds.PUFF);
				event.getRegistry().registerAll(ModSounds.WOOSH);
				event.getRegistry().registerAll(ModSounds.DOOT);
				event.getRegistry().registerAll(ModSounds.SHEP);
				event.getRegistry().registerAll(ModSounds.TRUMPET);
				event.getRegistry().registerAll(ModSounds.TM_BEEP);
				event.getRegistry().registerAll(ModSounds.HEARTBEAT);
				event.getRegistry().registerAll(ModSounds.SPOOKY);
				event.getRegistry().registerAll(ModSounds.RITZ);
				event.getRegistry().registerAll(ModSounds.HL3);
				event.getRegistry().registerAll(ModSounds.SQUID);
				event.getRegistry().registerAll(ModSounds.REVERB);
				event.getRegistry().registerAll(ModSounds.BURP);
				event.getRegistry().registerAll(ModSounds.RADIO_CLOSE);
				event.getRegistry().registerAll(ModSounds.DING_1);
				event.getRegistry().registerAll(ModSounds.DING_2);
				event.getRegistry().registerAll(ModSounds.DING_3);
				event.getRegistry().registerAll(ModSounds.DING_4);
				event.getRegistry().registerAll(ModSounds.DING_5);
				event.getRegistry().registerAll(ModSounds.DING_6);
				event.getRegistry().registerAll(ModSounds.DING_7);
				event.getRegistry().registerAll(ModSounds.OUTGOING_CALL);
				event.getRegistry().registerAll(ModSounds.SIT);
				event.getRegistry().registerAll(ModSounds.STARTCALL);
				event.getRegistry().registerAll(ModSounds.ENDCALL);
				event.getRegistry().registerAll(ModSounds.DTMF_0);
				event.getRegistry().registerAll(ModSounds.DTMF_1);
				event.getRegistry().registerAll(ModSounds.DTMF_2);
				event.getRegistry().registerAll(ModSounds.DTMF_3);
				event.getRegistry().registerAll(ModSounds.DTMF_4);
				event.getRegistry().registerAll(ModSounds.DTMF_5);
				event.getRegistry().registerAll(ModSounds.DTMF_6);
				event.getRegistry().registerAll(ModSounds.DTMF_7);
				event.getRegistry().registerAll(ModSounds.DTMF_8);
				event.getRegistry().registerAll(ModSounds.DTMF_9);
				event.getRegistry().registerAll(ModSounds.QUACK);
				event.getRegistry().registerAll(ModSounds.QUACKBOOM);
				event.getRegistry().registerAll(ModSounds.BAKA);
				event.getRegistry().registerAll(ModSounds.MALLET);
				event.getRegistry().registerAll(ModSounds.COOKING);
				event.getRegistry().registerAll(ModSounds.POLICE_HELMET);
				event.getRegistry().registerAll(ModSounds.KEKW);
				event.getRegistry().registerAll(ModSounds.PHONE_ACTIVATE);
				event.getRegistry().registerAll(ModSounds.TWO_YEARS);
				event.getRegistry().registerAll(ModSounds.LEOTEU_OFF);
				event.getRegistry().registerAll(ModSounds.LEOTEU_ON);
				event.getRegistry().registerAll(ModSounds.EXP);
				event.getRegistry().registerAll(ModSounds.LOUDBONG);
				event.getRegistry().registerAll(ModSounds.MEMORY);
				event.getRegistry().registerAll(ModSounds.BOOK_OPEN);
				event.getRegistry().registerAll(ModSounds.BOOK_CLOSE);
				event.getRegistry().registerAll(ModSounds.JINGLES);
				event.getRegistry().registerAll(ModSounds.RIP);
				event.getRegistry().registerAll(ModSounds.SUS1);
				event.getRegistry().registerAll(ModSounds.SUS2);
				event.getRegistry().registerAll(ModSounds.SPICY);
				event.getRegistry().registerAll(ModSounds.PHONE_UNLOCK);
				event.getRegistry().registerAll(ModSounds.OK1);
				event.getRegistry().registerAll(ModSounds.OK2);
				event.getRegistry().registerAll(ModSounds.DEATH);
				event.getRegistry().register(ModSounds.RING_1);
				event.getRegistry().register(ModSounds.RING_2);
				event.getRegistry().register(ModSounds.RING_3);
				event.getRegistry().register(ModSounds.RING_4);
				event.getRegistry().register(ModSounds.RING_5);
				event.getRegistry().register(ModSounds.RING_6);
				event.getRegistry().register(ModSounds.RING_7);
				event.getRegistry().register(ModSounds.RING_8);
				event.getRegistry().register(ModSounds.RING_9);
				event.getRegistry().register(ModSounds.RING_10);
				event.getRegistry().register(ModSounds.RING_11);
				event.getRegistry().register(ModSounds.DING_8);
				event.getRegistry().register(ModSounds.DING_9);
				event.getRegistry().register(ModSounds.RING_12);
				event.getRegistry().register(ModSounds.RING_13);
				event.getRegistry().register(ModSounds.RING_14);
				event.getRegistry().register(ModSounds.RING_15);
				event.getRegistry().register(ModSounds.RING_16);
				event.getRegistry().register(ModSounds.RING_17);
				event.getRegistry().register(ModSounds.RING_18);
				event.getRegistry().register(ModSounds.RING_19);
				event.getRegistry().register(ModSounds.RING_20);
				event.getRegistry().register(ModSounds.RING_21);
				event.getRegistry().register(ModSounds.RING_22);
				event.getRegistry().register(ModSounds.RING_23);
				event.getRegistry().register(ModSounds.RING_24);
				event.getRegistry().register(ModSounds.RING_25);
				event.getRegistry().register(ModSounds.MANHOLE_OPEN);
				event.getRegistry().register(ModSounds.MANHOLE_CLOSE);
				event.getRegistry().register(ModSounds.MANHOLE_BREAK);
				event.getRegistry().register(ModSounds.MANHOLE_PLACE);
				event.getRegistry().register(ModSounds.MANHOLE_STEP);
				event.getRegistry().register(ModSounds.BUSY);
				event.getRegistry().register(ModSounds.WATERPHONE);
				event.getRegistry().register(ModSounds.HEAL);
				event.getRegistry().register(ModSounds.GAVEL);
				event.getRegistry().register(ModSounds.ALERT_TONE);
				event.getRegistry().register(ModSounds.PHONE_OFF);
				event.getRegistry().register(ModSounds.MINEDROID_STARTUP);
				event.getRegistry().register(ModSounds.SPONGE_EQUIP);
				event.getRegistry().register(ModSounds.SPONGE_USE);
				event.getRegistry().register(ModSounds.FART_1);
				event.getRegistry().register(ModSounds.FART_2);
				event.getRegistry().register(ModSounds.FART_3);
				event.getRegistry().register(ModSounds.FART_4);
				event.getRegistry().register(ModSounds.FART_5);
				event.getRegistry().register(ModSounds.COUGH_M);
				event.getRegistry().register(ModSounds.COUGH_F);
				event.getRegistry().register(ModSounds.PHONE_CRASH);
				event.getRegistry().register(ModSounds.PHONE_BATTERY_LOW);
				event.getRegistry().register(ModSounds.PHONE_BOOTUP);
				event.getRegistry().register(ModSounds.BATTERY_LOW);
				event.getRegistry().register(ModSounds.CHISEL);
				event.getRegistry().register(ModSounds.SIT_1);
				event.getRegistry().register(ModSounds.SIT_2);
				event.getRegistry().register(ModSounds.SIT_3);
				event.getRegistry().register(ModSounds.SIT_4);
				event.getRegistry().register(ModSounds.SIT_5);
				event.getRegistry().register(ModSounds.PHONE_UNBOX);
				event.getRegistry().register(ModSounds.RATION_OPEN);
				event.getRegistry().register(ModSounds.TAPE_MEASURE_OPEN);
				event.getRegistry().register(ModSounds.TAPE_MEASURE_CLOSE);
				event.getRegistry().register(ModSounds.ALERT);
				event.getRegistry().register(ModSounds.NORMAL_BOOT);
				event.getRegistry().register(ModSounds.OOBE_BOOT);
				event.getRegistry().register(ModSounds.TOILET_1);
				event.getRegistry().register(ModSounds.TOILET_2);
				event.getRegistry().register(ModSounds.TOILET_3);
				event.getRegistry().register(ModSounds.URINAL);
				event.getRegistry().register(ModSounds.XP_STARTUP);
				event.getRegistry().register(ModSounds.WC_OFF);
				event.getRegistry().register(ModSounds.WC_ON);
				event.getRegistry().register(ModSounds.DING_10);
				event.getRegistry().register(ModSounds.BILL_ACCEPTOR);
				event.getRegistry().register(ModSounds.COIN_SLOT);
				event.getRegistry().register(ModSounds.POS_CASHBACK);
				event.getRegistry().register(ModSounds.POS_PAYMENT_TYPE);
				event.getRegistry().register(ModSounds.POS_SCAN);
				event.getRegistry().register(ModSounds.POS_SCANNER_BEEP);
				event.getRegistry().register(ModSounds.POS_SCANNER_MULTIBEEP);
				event.getRegistry().register(ModSounds.POS_TAKE_CARD);
				event.getRegistry().register(ModSounds.POS_USE_PINPAD);
				event.getRegistry().register(ModSounds.POS_WELCOME);
				event.getRegistry().register(ModSounds.PIANO);
				event.getRegistry().register(ModSounds.FRIDGE_OPEN);
				event.getRegistry().register(ModSounds.FRIDGE_CLOSE);
				event.getRegistry().register(ModSounds.COMING_OUT);
				event.getRegistry().register(ModSounds.AERO_STARTUP);
				event.getRegistry().register(ModSounds.DESK_BELL);
				event.getRegistry().register(ModSounds.DESK_BELL_AF);
				event.getRegistry().register(ModSounds.CAKE);
				event.getRegistry().register(ModSounds.HALLOW);
				event.getRegistry().register(ModSounds.ZAP);
				event.getRegistry().register(ModSounds.CARD_OUT);

				MinecraftForge.EVENT_BUS.register(new SoundRegisterListener());
				Main.logger.info("[" + Reference.MODNAME + " SoundLoader] Loaded");
			}
			catch(Exception ex)
			{
				Main.logger.error("[" + Reference.MODNAME + " ] Ah fuck, something broke...");
				Main.logger.error("[" + Reference.MODNAME + " ] ERROR IN SOUNDLOADER" + ex);
			}
		}
	}
}
